// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { HealthComponent, HealthComponentTableId } from "./tables/HealthComponent.sol";
import { AttackComponent, AttackComponentTableId } from "./tables/AttackComponent.sol";
import { DefenseComponent, DefenseComponentTableId } from "./tables/DefenseComponent.sol";
import { StaminaComponent, StaminaComponentTableId } from "./tables/StaminaComponent.sol";
import { StrengthComponent, StrengthComponentTableId } from "./tables/StrengthComponent.sol";
import { ConstitutionComponent, ConstitutionComponentTableId } from "./tables/ConstitutionComponent.sol";
import { DexterityComponent, DexterityComponentTableId } from "./tables/DexterityComponent.sol";
import { IntelligenceComponent, IntelligenceComponentTableId } from "./tables/IntelligenceComponent.sol";
